name:                makex5
version:             1.0.0.0
license:             BSD3
author:              "Andrew Butterfield"
maintainer:          "Andrew.Butterfield@scss.tcd.ie"
copyright:           "(c) 2023 Andrew Butterfield"


# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see README.md here

dependencies:
- base >= 4.7 && < 5
- csv
- containers
- utf8-string
- directory
- filepath
- process
- bytestring
- loc
- text
- HsYAML
- random

library:
  source-dirs: src

executables:

 
  makex5:
    main:            Main.lhs
    source-dirs:     makex5app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - makex5
    - random
 